const statuses = ['All', 'Scheduled', 'WIP', 'Observation Closure Pending', 'Pending Audit Manager Review', 'Rework Required', 'Resubmitted for Review', 'Completed', 'Overdue'];
const records = [
  { branchCode: '1001', branch: 'Pune Main', auditor: 'Rohit Shetty', week: '17 Aug - 22 Aug 2026', auditDate: '2026-08-22', due: '22 Aug 2026', status: 'Pending Audit Manager Review', pending: 0 },
  { branchCode: '1001', branch: 'Pune Main', auditor: 'Rohit Shetty', week: '10 Aug - 15 Aug 2026', auditDate: '2026-08-15', due: '15 Aug 2026', status: 'Completed', pending: 0 },
  { branchCode: '1001', branch: 'Pune Main', auditor: 'Amit Kulkarni', week: '24 Aug - 29 Aug 2026', auditDate: '2026-08-24', due: '29 Aug 2026', status: 'Scheduled', pending: 0 },
  { branchCode: '1002', branch: 'Mumbai Central', auditor: 'Neha Sharma', week: '17 Aug - 22 Aug 2026', auditDate: '2026-08-21', due: '22 Aug 2026', status: 'Rework Required', pending: 2 },
  { branchCode: '1002', branch: 'Mumbai Central', auditor: 'Neha Sharma', week: '03 Aug - 08 Aug 2026', auditDate: '2026-08-08', due: '08 Aug 2026', status: 'Completed', pending: 0 },
  { branchCode: '1002', branch: 'Mumbai Central', auditor: 'Vikram Shah', week: '10 Aug - 15 Aug 2026', auditDate: '2026-08-15', due: '15 Aug 2026', status: 'Resubmitted for Review', pending: 0 },
  { branchCode: '1003', branch: 'Nashik Branch', auditor: 'Rahul Menon', week: '17 Aug - 22 Aug 2026', auditDate: '2026-08-22', due: '22 Aug 2026', status: 'Observation Closure Pending', pending: 3 },
  { branchCode: '1003', branch: 'Nashik Branch', auditor: 'Rahul Menon', week: '03 Aug - 08 Aug 2026', auditDate: '2026-08-08', due: '08 Aug 2026', status: 'Overdue', pending: 0 },
  { branchCode: '1003', branch: 'Nashik Branch', auditor: 'Priya Nair', week: '24 Aug - 29 Aug 2026', auditDate: '2026-08-24', due: '29 Aug 2026', status: 'WIP', pending: 0 }
];
const savedHousekeepingReview = JSON.parse(sessionStorage.getItem('housekeepingReview') || '{}');
if (savedHousekeepingReview.branchCode && savedHousekeepingReview.status) { const savedRecord = records.find(item => item.branchCode === savedHousekeepingReview.branchCode); if (savedRecord) savedRecord.status = savedHousekeepingReview.status; }
let filtered = [...records];
let page = 1;
const pageSize = 4;
const statusFor = status => status === 'All' ? null : status;
let managerMode = 'audit';
function shell(content) { document.body.innerHTML = `<div class="app-main"><header class="app-header"><div><span class="header-parent">CAP Module</span><b>/</b><strong>List My Assigned Entities</strong></div><div class="app-user"><span class="avatar">AM</span> Priya Nair <small>Audit Manager</small></div></header><main class="app-content">${content}</main></div>`; }
  function pageMarkup() { return `<div class="page-heading"><div><span class="eyebrow">AUDIT MANAGER / MONITORING</span><h1>List My Assigned Entities</h1><p>Branch-level audit lifecycle for entities mapped to your team.</p></div><span class="total-chip">${filtered.length} audit records</span></div><div class="filters"><label>From Date<input id="fromDate" type="date" value="2026-04-01"></label><label>To Date<input id="toDate" type="date" value="2026-08-26"></label><button class="btn primary" data-manager-action="apply">Apply</button><button class="btn secondary" data-manager-action="reset">Reset</button><label class="search"><span>⌕</span><input id="managerSearch" placeholder="Search Branch / Code / Auditor"></label></div><div class="status-tabs manager-tabs">${statuses.map((status, index) => `<button class="manager-tab ${index === 0 ? 'selected' : ''}" data-manager-status="${status}">${status}<span>${status === 'All' ? records.length : records.filter(item => item.status === status).length}</span></button>`).join('')}</div><div class="list-head"><h2 id="managerTitle">All Assigned Audits</h2><span>${filtered.length} records</span></div><div class="assigned-table-wrap" id="managerAll"><table class="assigned-table"><thead><tr><th>Branch Code</th><th>Branch Name</th><th>Auditor Name</th>${statuses.slice(1).map(status => `<th>${status}</th>`).join('')}</tr></thead><tbody>${summaryRows()}</tbody></table></div><div class="manager-ticket-grid" id="managerTickets" hidden>${ticketRows()}</div><div class="pagination"><span>Page ${page} of ${Math.max(1, Math.ceil(filtered.length / pageSize))}</span><button class="btn secondary" data-manager-action="previous" ${page === 1 ? 'disabled' : ''}>Previous</button><button class="btn secondary" data-manager-action="next" ${page >= Math.ceil(filtered.length / pageSize) ? 'disabled' : ''}>Next</button></div>`; }
function summaryRows() { const grouped = [...new Map(records.map(item => [item.branchCode, item])).values()]; return grouped.map(item => { const branchRecords = records.filter(record => record.branchCode === item.branchCode); return `<tr><td><b>${item.branchCode}</b></td><td><strong>${item.branch}</strong></td><td>${[...new Set(branchRecords.map(record => record.auditor))].join(', ')}</td>${statuses.slice(1).map(status => `<td>${branchRecords.filter(record => record.status === status).length}</td>`).join('')}</tr>`; }).join(''); }
function ticketRows() { const start = (page - 1) * pageSize; return filtered.slice(start, start + pageSize).map(item => `<article class="manager-ticket"><div class="manager-ticket-head"><h3>${item.branch}</h3><span class="status-pill status-${item.status.toLowerCase().replaceAll(' ', '-')}" ><i></i>${item.status}</span></div><p class="manager-code">Branch Code: <b>${item.branchCode}</b></p><div class="manager-ticket-details"><span><small>Audit Week</small><b>${item.week}</b></span><span><small>Audit Date</small><b>${item.auditDate}</b></span><span><small>Due Date</small><b>${item.due}</b></span><span><small>Auditor Name</small><b>${item.auditor}</b></span>${item.pending ? `<span><small>Pending Observation Count</small><b>${item.pending}</b></span>` : ''}</div><button class="btn primary manager-review" data-manager-action="view" data-branch-code="${item.branchCode}">${item.status === 'Pending Audit Manager Review' || item.status === 'Resubmitted for Review' ? 'Perform Audit Review' : item.status === 'Rework Required' ? 'Review Audit' : 'View Audit'}</button></article>`).join('') || '<p class="no-results">No audits match the selected filters.</p>'; }
function filterRows() { const query = document.getElementById('managerSearch').value.toLowerCase().trim(); const from = new Date(document.getElementById('fromDate').value || '1900-01-01'); const to = new Date(document.getElementById('toDate').value || '2999-12-31'); filtered = records.filter(item => new Date(item.auditDate) >= from && new Date(item.auditDate) <= to && (!query || `${item.branchCode} ${item.branch} ${item.auditor}`.toLowerCase().includes(query))); page = 1; render(); }
function applyManagerMode() { if (managerMode !== 'housekeeping') return; const housekeepingActions = { WIP: 'View Review of Internal / Office accounts', 'Pending Audit Manager Review': 'Review Review of Internal / Office accounts', 'Pending AM Review': 'Review Review of Internal / Office accounts', 'Rework Required': 'View Review of Internal / Office accounts', 'Resubmitted for Review': 'View Review of Internal / Office accounts', Completed: 'View Review of Internal / Office accounts' }; document.querySelectorAll('[data-manager-status="Observation Closure Pending"]').forEach(tab => tab.remove()); document.querySelectorAll('#managerAll tr').forEach(row => row.children[5]?.remove()); document.querySelectorAll('.manager-ticket').forEach(ticket => { const values = ticket.querySelectorAll('.manager-ticket-details span'); if (values[0]) { values[0].querySelector('small').textContent = 'Review of Internal / Office accounts Month'; values[0].querySelector('b').textContent = '24 Aug - 29 Aug 2026'; } if (values[1]) { values[1].querySelector('small').textContent = 'Start Date'; values[1].querySelector('b').textContent = '2026-08-24'; } if (values[2]) { values[2].querySelector('small').textContent = 'Due Date'; values[2].querySelector('b').textContent = '29 Aug 2026'; } const status = ticket.querySelector('.status-pill')?.textContent.trim(); const button = ticket.querySelector('.manager-review'); if (button) button.textContent = housekeepingActions[status] || 'View Review of Internal / Office accounts'; }); }
function render() { shell(pageMarkup()); bind(); const section = document.createElement('div'); section.className = 'queue-sections'; section.innerHTML = `<button class="queue-section ${managerMode === 'audit' ? 'active' : ''}" data-manager-mode="audit">Perform Audit</button><button class="queue-section ${managerMode === 'housekeeping' ? 'active' : ''}" data-manager-mode="housekeeping">Review of Internal / Office accounts</button>`; document.querySelector('.page-heading').after(section); document.querySelectorAll('[data-manager-mode]').forEach(button => button.onclick = () => { managerMode = button.dataset.managerMode; render(); }); applyManagerMode(); }
function bind() { document.getElementById('managerSearch').oninput = filterRows; document.querySelectorAll('[data-manager-status]').forEach(tab => tab.onclick = () => { const selected = statusFor(tab.dataset.managerStatus); filtered = records.filter(item => !selected || item.status === selected); page = 1; document.querySelectorAll('[data-manager-status]').forEach(item => item.classList.toggle('selected', item === tab)); document.getElementById('managerTitle').textContent = tab.dataset.managerStatus === 'All' ? 'All Assigned Audits' : tab.dataset.managerStatus; document.getElementById('managerAll').hidden = tab.dataset.managerStatus !== 'All'; document.getElementById('managerTickets').hidden = tab.dataset.managerStatus === 'All'; document.getElementById('managerTickets').innerHTML = ticketRows(); document.querySelector('.pagination span').textContent = `Page ${page} of ${Math.max(1, Math.ceil(filtered.length / pageSize))}`; bind(); }); document.querySelectorAll('[data-manager-action]').forEach(control => control.onclick = () => { const action = control.dataset.managerAction; if (action === 'apply') filterRows(); if (action === 'reset') { document.getElementById('fromDate').value = '2026-04-01'; document.getElementById('toDate').value = '2026-08-26'; document.getElementById('managerSearch').value = ''; filtered = [...records]; page = 1; render(); } if (action === 'previous') { page--; render(); } if (action === 'next') { page++; render(); } if (action === 'view') { const branch = records.find(item => item.branchCode === control.dataset.branchCode); if (managerMode === 'housekeeping') { sessionStorage.setItem('capAuditContext', JSON.stringify({ branch: branch?.branch || 'Selected Branch', code: branch?.branchCode || 'BR-1042', auditor: branch?.auditor || 'Rohit Shetty', week: branch?.week || '24 Aug - 29 Aug 2026', status: branch?.status || 'Pending Audit Manager Review' })); window.location.href = '10-review-internal-office-accounts.html'; } else window.location.href = '06-perform-audit-review.html'; } }); }
render();
document.addEventListener('click', event => { if (event.target.closest('[data-manager-status]')) setTimeout(applyManagerMode, 0); });
